# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'airlines.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 1010)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.userBtn = QtWidgets.QPushButton(self.centralwidget)
        self.userBtn.setGeometry(QtCore.QRect(250, 190, 321, 41))
        self.userBtn.setObjectName("userBtn")
        self.adminBtn = QtWidgets.QPushButton(self.centralwidget)
        self.adminBtn.setGeometry(QtCore.QRect(250, 260, 321, 41))
        self.adminBtn.setObjectName("adminBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 50, 351, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 160, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(-50, 0, 891, 1100))
        self.label_3.setStyleSheet("background-image:url(:/newPrefix/photo-1531642765602-5cae8bbbf285.jpg)")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/photo-1531642765602-5cae8bbbf285.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.managerBtn = QtWidgets.QPushButton(self.centralwidget)
        self.managerBtn.setGeometry(QtCore.QRect(250, 330, 321, 41))
        self.managerBtn.setObjectName("managerBtn")
        self.label_3.raise_()
        self.userBtn.raise_()
        self.adminBtn.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.managerBtn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Airlines"))
        self.userBtn.setText(_translate("MainWindow", "Login as Passenger"))
        self.adminBtn.setText(_translate("MainWindow", "Login as Admin"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Welcome to Airlines !</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Please choose your Login"))
        self.managerBtn.setText(_translate("MainWindow", "Login as Flight Manager"))
import background_rc
