# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'animalAdd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 210)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 90, 201, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.nameLb = QtWidgets.QLabel(Form)
        self.nameLb.setGeometry(QtCore.QRect(20, 30, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.nameLb.setFont(font)
        self.nameLb.setObjectName("nameLb")
        self.typeLb = QtWidgets.QLabel(Form)
        self.typeLb.setGeometry(QtCore.QRect(470, 30, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.typeLb.setFont(font)
        self.typeLb.setObjectName("typeLb")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(320, 90, 291, 41))
        self.comboBox.setObjectName("comboBox")
        self.add = QtWidgets.QPushButton(Form)
        self.add.setGeometry(QtCore.QRect(500, 150, 111, 41))
        self.add.setObjectName("add")
        self.decline = QtWidgets.QPushButton(Form)
        self.decline.setGeometry(QtCore.QRect(10, 150, 111, 41))
        self.decline.setObjectName("decline")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.nameLb.setText(_translate("Form", "Enter name:"))
        self.typeLb.setText(_translate("Form", "Choose type:"))
        self.add.setText(_translate("Form", "Add"))
        self.decline.setText(_translate("Form", "Decline"))
