# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'animalsAsk.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(697, 183)
        self.askAniamals = QtWidgets.QLabel(Dialog)
        self.askAniamals.setGeometry(QtCore.QRect(20, 20, 661, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.askAniamals.setFont(font)
        self.askAniamals.setObjectName("askAniamals")
        self.yes = QtWidgets.QPushButton(Dialog)
        self.yes.setGeometry(QtCore.QRect(440, 110, 111, 41))
        self.yes.setObjectName("yes")
        self.no = QtWidgets.QPushButton(Dialog)
        self.no.setGeometry(QtCore.QRect(560, 110, 111, 41))
        self.no.setObjectName("no")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.askAniamals.setText(_translate("Dialog", "Do you want to add any of your animals on the flight ?"))
        self.yes.setText(_translate("Dialog", "Yes"))
        self.no.setText(_translate("Dialog", "No"))
