# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'animalDelete.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(461, 161)
        self.decline = QtWidgets.QPushButton(Form)
        self.decline.setGeometry(QtCore.QRect(10, 110, 111, 41))
        self.decline.setObjectName("decline")
        self.confirm = QtWidgets.QPushButton(Form)
        self.confirm.setGeometry(QtCore.QRect(340, 110, 111, 41))
        self.confirm.setObjectName("confirm")
        self.animalLb = QtWidgets.QLabel(Form)
        self.animalLb.setGeometry(QtCore.QRect(20, 40, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.animalLb.setFont(font)
        self.animalLb.setObjectName("animalLb")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.decline.setText(_translate("Form", "Decline"))
        self.confirm.setText(_translate("Form", "Confirm"))
        self.animalLb.setText(_translate("Form", "Are you sure you want ot delete animal?"))
