# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flightsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1007, 706)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.departureLb = QtWidgets.QLabel(self.centralwidget)
        self.departureLb.setGeometry(QtCore.QRect(10, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.departureLb.setFont(font)
        self.departureLb.setObjectName("departureLb")
        self.arrivalLb = QtWidgets.QLabel(self.centralwidget)
        self.arrivalLb.setGeometry(QtCore.QRect(230, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.arrivalLb.setFont(font)
        self.arrivalLb.setObjectName("arrivalLb")
        self.departureCb = QtWidgets.QComboBox(self.centralwidget)
        self.departureCb.setGeometry(QtCore.QRect(10, 60, 181, 31))
        self.departureCb.setObjectName("departureCb")
        self.arrivalCb = QtWidgets.QComboBox(self.centralwidget)
        self.arrivalCb.setGeometry(QtCore.QRect(220, 60, 181, 31))
        self.arrivalCb.setObjectName("arrivalCb")
        self.dateLb = QtWidgets.QLabel(self.centralwidget)
        self.dateLb.setGeometry(QtCore.QRect(440, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateLb.setFont(font)
        self.dateLb.setObjectName("dateLb")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(440, 50, 312, 183))
        self.calendarWidget.setObjectName("calendarWidget")
        self.flightsLb = QtWidgets.QLabel(self.centralwidget)
        self.flightsLb.setGeometry(QtCore.QRect(40, 190, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.flightsLb.setFont(font)
        self.flightsLb.setObjectName("flightsLb")
        self.flightsScroll = QtWidgets.QScrollArea(self.centralwidget)
        self.flightsScroll.setGeometry(QtCore.QRect(20, 250, 791, 411))
        self.flightsScroll.setWidgetResizable(True)
        self.flightsScroll.setObjectName("flightsScroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 789, 409))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.flightsScroll.setWidget(self.scrollAreaWidgetContents)
        self.backBt = QtWidgets.QPushButton(self.centralwidget)
        self.backBt.setGeometry(QtCore.QRect(830, 80, 141, 51))
        self.backBt.setObjectName("backBt")
        self.showFlightsBt = QtWidgets.QPushButton(self.centralwidget)
        self.showFlightsBt.setGeometry(QtCore.QRect(830, 150, 141, 61))
        self.showFlightsBt.setObjectName("showFlightsBt")
        self.nextBt = QtWidgets.QPushButton(self.centralwidget)
        self.nextBt.setGeometry(QtCore.QRect(860, 600, 121, 51))
        self.nextBt.setObjectName("nextBt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1007, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "flightsPage"))
        self.departureLb.setText(_translate("MainWindow", "Departure city:"))
        self.arrivalLb.setText(_translate("MainWindow", "Arrival city:"))
        self.dateLb.setText(_translate("MainWindow", "Date:"))
        self.flightsLb.setText(_translate("MainWindow", "Actual flight at your direction:"))
        self.backBt.setText(_translate("MainWindow", "Go Back"))
        self.showFlightsBt.setText(_translate("MainWindow", "Show flights"))
        self.nextBt.setText(_translate("MainWindow", "Go next"))
