# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forAnotherBuy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(907, 259)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(710, 20, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.patronumic = QtWidgets.QLineEdit(Form)
        self.patronumic.setGeometry(QtCore.QRect(480, 90, 181, 41))
        self.patronumic.setObjectName("patronumic")
        self.next = QtWidgets.QPushButton(Form)
        self.next.setGeometry(QtCore.QRect(750, 160, 141, 51))
        self.next.setObjectName("next")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(290, 20, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 20, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.firstname = QtWidgets.QLineEdit(Form)
        self.firstname.setGeometry(QtCore.QRect(40, 90, 181, 41))
        self.firstname.setObjectName("firstname")
        self.surname = QtWidgets.QLineEdit(Form)
        self.surname.setGeometry(QtCore.QRect(260, 90, 181, 41))
        self.surname.setObjectName("surname")
        self.back = QtWidgets.QPushButton(Form)
        self.back.setGeometry(QtCore.QRect(40, 170, 141, 51))
        self.back.setObjectName("back")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(490, 20, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.passport = QtWidgets.QLineEdit(Form)
        self.passport.setGeometry(QtCore.QRect(710, 90, 181, 41))
        self.passport.setObjectName("passport")
        self.sign = QtWidgets.QPushButton(Form)
        self.sign.setGeometry(QtCore.QRect(590, 160, 141, 51))
        self.sign.setObjectName("sign")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "forAnotherBuy"))
        self.label_4.setText(_translate("Form", "Enter passport code:"))
        self.next.setText(_translate("Form", "Go next"))
        self.label_2.setText(_translate("Form", "Enter surname:"))
        self.label.setText(_translate("Form", "Enter firstname:"))
        self.back.setText(_translate("Form", "Go back"))
        self.label_3.setText(_translate("Form", "Enter patronymic:"))
        self.sign.setText(_translate("Form", "Sign In"))
