# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(592, 436)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 20, 551, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.leLogin = QtWidgets.QLineEdit(Form)
        self.leLogin.setGeometry(QtCore.QRect(170, 90, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.leLogin.setFont(font)
        self.leLogin.setObjectName("leLogin")
        self.lePass = QtWidgets.QLineEdit(Form)
        self.lePass.setGeometry(QtCore.QRect(170, 150, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lePass.setFont(font)
        self.lePass.setObjectName("lePass")
        self.loginBtn = QtWidgets.QPushButton(Form)
        self.loginBtn.setGeometry(QtCore.QRect(340, 220, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loginBtn.setFont(font)
        self.loginBtn.setObjectName("loginBtn")
        self.backBtn = QtWidgets.QPushButton(Form)
        self.backBtn.setGeometry(QtCore.QRect(170, 220, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.backBtn.setFont(font)
        self.backBtn.setObjectName("backBtn")
        #self.label_2 = QtWidgets.QLabel(Form)
       # self.label_2.setGeometry(QtCore.QRect(170, 290, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        #self.label_2.setFont(font)
        #self.label_2.setObjectName("label_2")
        #self.signBtn = QtWidgets.QPushButton(Form)
        #self.signBtn.setGeometry(QtCore.QRect(170, 330, 261, 51))
        #self.signBtn.setObjectName("signBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "loginUser"))
        self.label.setText(_translate("Form", "Please enter your login and password:"))
        self.loginBtn.setText(_translate("Form", "Login"))
        self.backBtn.setText(_translate("Form", "Go back"))
        #self.label_2.setText(_translate("Form", "Don\'t have an accaount?"))
        #self.signBtn.setText(_translate("Form", "Sign In"))
