# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(656, 374)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 30, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(260, 30, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(460, 30, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.firstname = QtWidgets.QLineEdit(Form)
        self.firstname.setGeometry(QtCore.QRect(10, 100, 181, 41))
        self.firstname.setObjectName("firstname")
        self.surname = QtWidgets.QLineEdit(Form)
        self.surname.setGeometry(QtCore.QRect(230, 100, 181, 41))
        self.surname.setObjectName("surname")
        self.patronumic = QtWidgets.QLineEdit(Form)
        self.patronumic.setGeometry(QtCore.QRect(450, 100, 181, 41))
        self.patronumic.setObjectName("patronumic")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.passport = QtWidgets.QLineEdit(Form)
        self.passport.setGeometry(QtCore.QRect(10, 230, 181, 41))
        self.passport.setObjectName("passport")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(280, 160, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.login = QtWidgets.QLineEdit(Form)
        self.login.setGeometry(QtCore.QRect(230, 230, 181, 41))
        self.login.setObjectName("login")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(450, 230, 181, 41))
        self.password.setObjectName("password")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(470, 160, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.sign = QtWidgets.QPushButton(Form)
        self.sign.setGeometry(QtCore.QRect(490, 310, 141, 51))
        self.sign.setObjectName("sign")
        self.back = QtWidgets.QPushButton(Form)
        self.back.setGeometry(QtCore.QRect(10, 310, 141, 51))
        self.back.setObjectName("back")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "signIn"))
        self.label.setText(_translate("Form", "Enter firstname:"))
        self.label_2.setText(_translate("Form", "Enter surname:"))
        self.label_3.setText(_translate("Form", "Enter patronymic:"))
        self.label_4.setText(_translate("Form", "Enter passport code:"))
        self.label_5.setText(_translate("Form", "Enter login:"))
        self.label_6.setText(_translate("Form", "Enter password:"))
        self.sign.setText(_translate("Form", "Sign In"))
        self.back.setText(_translate("Form", "Go back"))
